### ISSUE TITLE
RDP access  probem win11 debloated

### ISSUE THREAD

**Issue by abdouabdou123** [amjiddader/windows-on-cloud#1]
Hello, I can't access the server using RDP I can only use tightVPC .
What's the problem.

I tried to activate the remote access on the device , I am unable to access it , I think it's a bug or something.

windows 11 (debloated)

**Comment by amjiddader** [comment]
What error you get...

It may be error from your Side. as i have checked it worked fine.

Also i recommend tightvnc or realVNC ( change port & password) tightvnc is faster.

If u need winfows RDP send me error log or screenshot.

**Comment by amjiddader** [comment]
Now marked as close ..
