### ISSUE TITLE
Not Opening Windows

### ISSUE THREAD

**Issue by acerhizmq** [amjiddader/windows-on-cloud#2]
I did all the steps, when I change the recovery mode to the hard disk and start from the console, the grub gives an error. Not opening Windows

I'm trying to download stock Windows 11 using your command file.

VPS : 
Premium AMD 4 vCPU 
16GB Ram

**Comment by amjiddader** [comment]
Where you get this error? 
In RDP , shell, or web consol...

Also.. 
If you double check the guide it should work.
Note: do not mount disk in recovery mode.
+ once installed, re-start your VM ( even in recovery) setup networking.

You can then connect with RDP ( windows 11 lite is recommended)
