### ISSUE TITLE
Any tuts for creating own windows template?

### ISSUE THREAD

**Issue by YoruAkio** [amjiddader/windows-on-cloud#3]
I wanna know how to make my own windows template for digital ocean, I've tried to make it but the ethernet is not detected idk what is the problem if u know please make the tutorial more details step by step

**Comment by amjiddader** [comment]
You need to use virtio - i.e: Virtual Network in your ISO / Image before installing OS . \
First install windows with virtio-win on a PC or on on same droplet \
Using GUI install windows and then install drivers from virtio-win.iso and setup everything.

Then export this OS as raw image using qemu.

if you do not know how to use qemu to create images you can search on Gooogle
