### ISSUE TITLE
Rdp windows 10 authentication error

### ISSUE THREAD

**Issue by navtemmt** [amjiddader/windows-on-cloud#4]
Hello thanks for sharing the guide, appreciate very much !  Successfully install window 10 but the problem is when I rdp it shows authentication error, 

Here are the screenshot of error, can you please look into it, thank you

![image](https://github.com/amjiddader/windows-on-cloud/assets/83179960/7663a016-9855-412d-8c8c-b6af0b1e46fb)

**Comment by amjiddader** [comment]
Yes this is mentioned in readme file.

So you can use tightvnc/realvnc ..
You can disable this from security.

**Comment by navtemmt** [comment]
> Yes this is mentioned in readme file.
> 
> So you can use tightvnc/realvnc .. You can disable this from security.

Maybe i missed where you mentioned..haha

Yes tightvnc is working good, thanks !

**Comment by amjiddader** [comment]
tightvnc should work as expected. As for RDP its not an issue for CLIENT ( VPS) \
It is because windows blocks remote access for security issues and any new update patchers security.

Can be disabled from windows setting ( on both host+client)
